### ISSUE TITLE
Pipeline should output ExpressionSet w/ gene annotation

### ISSUE THREAD

**Issue by montilab** [montilab/pipeliner#34]
Pipeline should output an ExpressionSet (in addition to a tab-delimited expression matrix) for each of the counting outputs (stringty, HTseq, FeatureCount, ...)

Look at Hydra code for examples

- [x] featurecounts
- [x] htseq
- [x] stringtie

**Comment by anfederico** [comment]
Working for htseq and featurecounts. Outputs an .rds file which can be loaded into R as an expression set as well as a tab-delimited expression matrix.

**Comment by anfederico** [comment]
Need to parse the merged gtf to find reference gene ids. Stringtie uses custom tags which break the expression set process when it tried to re-parse the gtf file.

**Comment by anfederico** [comment]
Should add a new option `-A path/to/abundances.tab` and filter out transcripts with only STRG ids.
