### ISSUE TITLE
pipeliner should be running anywhere

### ISSUE THREAD

**Issue by tetomonti** [montilab/pipeliner#45]
See if it's possible to have pipeliner work as an actual tool that, once installed, can be run from anywhere (once its path is included in the $path variable). 

Right now, having to clone pipeliner for each user who wants to use it, and then having to run all the runs (even if about unrelated projects/studies) from the same pipeliner folder (or, conversely, having to create a different installation of pipeliner for each project/study) is not good practice.

**Comment by anfederico** [comment]
I believe this is now possible in later versions of Nextflow: https://www.nextflow.io/docs/latest/sharing.html. However the pipelines would need to be separated into dedicated repositores and renamed to `main.nf` to enable running in a format like:

`nextflow run http://github.com/montilab/pipeliner ...`
