### ISSUE TITLE
No license specified

### ISSUE THREAD

**Issue by lebovic** [montilab/pipeliner#48]
There's currently no license specified for this project, but I'm on a team that's interested in using this project.

Can a license be added? Right now, having no license retains exclusive copyright ([choosealicense.com/no-permission/](https://choosealicense.com/no-permission/)).

**Comment by anfederico** [comment]
The license is MIT, per our pre-print (https://www.biorxiv.org/content/10.1101/476515v1). I also added the license to the GitHub. Enjoy!

**Comment by lebovic** [comment]
Great! Thanks for the quick addition.
