### ISSUE TITLE
stranded option for htseq and featureCounts 

### ISSUE THREAD

**Issue by mmkhan19** [montilab/pipeliner#49]
Hi,

Please add the strandedness option for htseq and featureCounts quantifier. 

Thanks,
Muzamil

**Comment by anfederico** [comment]
Posting the solution here for future reference.

All processes have `xargs` and `ainj` optional parameters that can be set in the config which are used to pass additional arguments to a tool when the argument cannot be directly set in the config.

`params.{process}.xargs`: Any number of custom arguments when calling the main tool
`params.{process}.ainj`: A custom post-processing script injected after the main tool

e.g.
```bash
samtools view ${bamfiles} | \
htseq-count \
$params.htseq.xargs \
--type $params.htseq.type \
--mode $params.htseq.mode \
...
```
